package hr.fer.zemris.java.custom.scripting.lexer;

/**
 * This class represents a token generated by SmartScriptLexer to
 * process given text and encapsulate elements of the document.
 * @author Petra Barać
 *
 */

public class SmartScriptToken {
	/**
	 * value that it encapsulates
	 */
	private Object value;
	
	/**
	 * Type of token
	 */
	private SmartScriptTokenType type;
	
	/**
	 * Default constructor
	 * @param type type of token
	 * @param value stored value
	 */
	
	public SmartScriptToken(SmartScriptTokenType type, Object value) {
		
		this.type = type;
		this.value = value;

	}
	
	/**
	 * Get private variable value
	 * @return value
	 */
	public Object getValue() {
		return value;
	}
	/**
	 * Get private variable type
	 * @return type of token
	 */
	public SmartScriptTokenType getType() {
		return type;
	}
	
}
