package hr.fer.zemris.java.hw03.prob1;

/**
* This class represents a token generated by Lexer to
* process given text and encapsulate elements of the document.
 * @author Petra Barać
 *
 */


public class Token {
	/**
	 * value that it encapsulates
	 */
	private TokenType type;
	
	/**
	 * Type of token
	 */
	private Object value;
	
	/**
	 * Default constructor that takes two parameters
	 * @param type type of token
	 * @param value value that it encapsulates
	 */
		
	public Token(TokenType type, Object value) {
		this.type = type;
		this.value = value;
	}
	
	/**
	 * Getter method for value
	 * @return value of token
	 */
	public Object getValue() {
		return value;
	}
	
	/**
	 * Getter method for type
	 * @return type of token
	 */
	public TokenType getType() {
		return type;
	}
		
}
